### ISSUE TITLE
Cannot Found 'dist/index.js' file in this package.

### ISSUE THREAD

**Issue by novamaster-git** [mrlaessig/react-native-autocomplete-input#261]
**Getting this error when i try to use this package:**

```
error: Error: While trying to resolve module `react-native-autocomplete-input` from file `/home/nova/Projects/RN/{YOUR_APP_DIR}/src/screen/App/Groups/sendAlert.tsx`, the package `/home/nova/Projects/RN/{YOUR_APP_DIR}/node_modules/react-native-autocomplete-input/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/home/nova/Projects/RN/{YOUR_APP_DIR}/node_modules/react-native-autocomplete-input/dist/index.js`. Indeed, none of these files exist:

  * /home/nova/Projects/RN/{YOUR_APP_DIR}/node_modules/react-native-autocomplete-input/dist/index.js(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * /home/nova/Projects/RN/{YOUR_APP_DIR}/node_modules/react-native-autocomplete-input/dist/index.js/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at DependencyGraph.resolveDependency (/home/nova/Projects/RN/{YOUR_APP_DIR}/node_modules/metro/src/node-haste/DependencyGraph.js:311:17)
    at Object.resolve (/home/nova/Projects/RN/{YOUR_APP_DIR}/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/home/nova/Projects/RN/{YOUR_APP_DIR}/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /home/nova/Projects/RN/{YOUR_APP_DIR}/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/home/nova/Projects/RN/{YOUR_APP_DIR}/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/home/nova/Projects/RN/{YOUR_APP_DIR}/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at async addDependency (/home/nova/Projects/RN/{YOUR_APP_DIR}/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)
    at async Promise.all (index 34)
    at async processModule (/home/nova/Projects/RN/{YOUR_APP_DIR}/node_modules/metro/src/DeltaBundler/traverseDependencies.js:198:5)
```

> React Native: 0.66.4
> React: 17.0.2
> Android and ios
> node: 16

**Comment by novamaster-git** [comment]
Just downgraded the version to `5.0.0` and its working.
Thank you for your support.

**Comment by novamaster-git** [comment]
> Hey @novamaster-git, you should be able to install the latest release as well. Did you try to` rm -rf node_modules` and install the dependencies again?

The latest Version is not working. showing the above error.
Does the new version dependent on node version?
i am using node v16 and it is showing this error but when i use node v18 it working fine
